default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: "asw_postgres"
  password: "asw_postgres"
  pool: 5

development:
  <<: *default
  database: myapp_development

test:
  <<: *default
  database: myapp_test
